### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by cfoellmann** [wp-api-libraries/wp-api-libraries.com#3]
Hi guys,

I am very interested and really want to get involved.
What are you planning to use As channels for communication?
Are you planning on opening up a Slack Team to get people to talk to each other?
Set up a project management tool like Asana or Trello for collaboration?

**Comment by sfgarza** [comment]
Hello and welcome,

We are glad to have you!
We've set up a [wp-api-libraries](https://wp-api-libraries.slack.com) slack team as the main channel of communication. As for project management we're planning to use GitHub's new 'Projects' feature.
