### ISSUE TITLE
WP-API Client Library. 

### ISSUE THREAD

**Issue by thinkstylestudio** [wp-api-libraries/wp-api-libraries.com#8]
For WP->WP interactions.

**Comment by bhubbard** [comment]
@thinkstylestudio Can you clarify? Not sure what your asking?

**Comment by thinkstylestudio** [comment]
@bhubbard For sure, I was on the prowl in aims to find a php library that abstracted interactions /w the WP-API. Basically something like [this](https://github.com/WP-API/client-php) or [this](https://github.com/Automattic/wp-rest-php-lib) but of course actively updated.

**Comment by bhubbard** [comment]
@thinkstylestudio Yeah we don't have a client specific to the WordPress Rest API, the two that you provided are probably the best at this moment, and I would stick with those. 

We are not affiliated with Automattic, and the repo/projects this org is focused on is WordPress php libraries for third-party APIs.

**Comment by thinkstylestudio** [comment]
cool and thanks!
