### ISSUE TITLE
DoneDone - The Simple Bug and Issue Tracker

### ISSUE THREAD

**Issue by leepeterson** [wp-api-libraries/wp-api-libraries.com#9]
[DoneDone](https://www.getdonedone.com) is the simple bug and issue tracker, beloved for simple issue workflow and unique
approach to merging issue tracking with customer support. No more complex software or messy spreadsheets to track issues and support tickets. Just one uncomplicated, central hub.

Documentation for version 2 of the DoneDone Developer API can be found [here](https://www.getdonedone.com/api/). For guidance, an old PHP 5.3 wrapper for v1 of their API can be found [here](https://github.com/GetDoneDone/DoneDone-API-PHP).

**Comment by bhubbard** [comment]
Created a empty repo for it. https://github.com/wp-api-libraries/wp-getdonedone-api

Feel free to get it started and submit a pull request for it.
